apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: chachara-backend
  template:
    metadata:
      annotations:
        rollout-date: {{ now | quote }}
      labels:
        app: chachara-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - secretRef:
                name: chachara-secrets  
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx128m -Xms128m -XX:+UseSerialGC -XX:ActiveProcessorCount=1"
          resources:
            limits:
              cpu: "0.5"
              memory: "256Mi"
            requests:
              cpu: "0.2"
              memory: "128Mi"