apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: chachara-backend
  template:
    metadata:
      labels:
        app: chachara-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - secretRef:
                name: chachara-secrets  # <-- Kubernetes busca el secreto
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"