apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: chachara-backend
  template:
    metadata:
      annotations:
        rollout-date: {{ now | quote }}
      labels:
        app: chachara-backend
    spec:
      # Obliga a Kubernetes a correr este pod en el servidor Red Hat
      nodeSelector:
        rol: backend
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - secretRef:
                name: chachara-secrets  
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"