apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: chachara-frontend
  template:
    metadata:
      annotations:
        rollout-date: {{ now | quote }}
      labels:
        app: chachara-frontend
    spec:
      # Obliga a Kubernetes a correr este pod en el servidor Ubuntu
      nodeSelector:
        rol: frontend
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.frontend.port }}